language: node_js

services:
  - mongodb

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"

after_success:
  - "npm run test:cov"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
