language: node_js

services:
  - mongodb
  - redis-server

node_js:
  - "iojs"
  - "0.12"
  - "0.10"

after_success:
  - "npm run test:cov"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
