language: node_js

services:
  - mongodb

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

after_success:
  - "npm run test:cov"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
